export const GET_PRODUCTS_START = "GET_PRODUCTS_START";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";


export const GET_WISHLIST_START = "GET_WISHLIST_START";
export const GET_WISHLIST_SUCCESS = "GET_WISHLIST_SUCCESS";
export const GET_WISHLIST_ERROR = "GET_WISHLIST_ERROR";

export const GET_ADDTOBAG_START = "GET_ADDTOBAG_START";
export const GET_ADDTOBAG_SUCCESS = "GET_ADDTOBAG_SUCCESS";
export const GET_ADDTOBAG_ERROR = "GET_ADDTOBAG_ERROR";
